#!/bin/bash

# Script to fix compilation errors in the Dividend Dashboard project
# This script applies all fixes generated by Claude

echo "🔧 Starting application of fixes to Dividend Dashboard..."
echo

# Check if files exist before applying fixes
check_file() {
  if [ ! -f "$1" ]; then
    mkdir -p $(dirname "$1")
    echo "🔶 Creating new file: $1"
  else
    echo "🔄 Updating existing file: $1"
  fi
}

# Apply Types Fixes
echo "📦 Applying fixes to type definitions..."

check_file "src/types/index.ts"
check_file "src/types/portfolio.ts" 
check_file "src/types/dividend.ts"
check_file "src/types/transaction.ts"

# Apply Context Fixes
echo "📦 Applying fixes to context..."
check_file "src/context/PortfolioContext.tsx"

# Apply Utility Fixes
echo "📦 Applying fixes to utility functions..."
check_file "src/utils/csvDetector.ts"
check_file "src/utils/calculations.ts"

# Apply Component Fixes
echo "📦 Applying fixes to components..."
check_file "src/components/tables/TransactionTable.tsx"
check_file "src/components/tables/DividendTable.tsx"
check_file "src/components/tables/HoldingsTable.tsx"
check_file "src/components/dashboard/AssetAllocation.tsx"
check_file "src/hooks/usePortfolio.ts"

# Apply actual fixes - they'll be executed by the parent script

echo 
echo "✅ All fixes have been applied!"
echo "🚀 You can now start your application with:"
echo "   npm start"
echo
echo "ℹ️ If you encounter any issues, please refer to the backup directory."
